### ISSUE TITLE
昨年の受講情報を追加する

### ISSUE THREAD

**Issue by chiroruxx** [chiroruxx/aiit-syllabus-2021#7]
slackから。

> 各講義、昨年受講生の人数と評点別分布表があるらしいんですが、一緒に参照できるといいなーと。人気度と難度の参考にしたいです。できそうだったら、なにとぞ実装してください。

**Comment by konny0311** [comment]
リンク貼っておきます。
https://aiit.ac.jp/support/disclosure.html
